export const DEFAULT_HOME_CONTENT = {
    "title": "實驗室簡介 (About Us)",
    "paragraph1": "歡迎來到生物資訊演算與控制實驗室。在這裡，我們將抽象的數學理論轉化為真實的物理運動。實驗室目前專注於無人機控制 (UAV Control)、嵌入式系統、人工智慧、生醫科技和音訊處理等領域的研究。",
    "paragraph2": "我們的願景是將尖端的控制理論轉化為高強健性的演算法，並實踐於各種飛行載具與嵌入式平台中，解決複雜環境下的工程挑戰。"
};

export const DEFAULT_PROFESSOR_CONTENT = {
    "chineseName": "林俊良 博士",
    "englishName": "Dr. Chun-Liang Lin",
    "education": "國立成功大學航太工程博士",
    "position": "國立中興大學 中興講座教授",
    "researchAreas": "控制系統數學、生物辨識、導引/導航與控制、能源控制",
    "email": "chunlin@dragon.nchu.edu.tw",
    "phone": "+886-4-22851549 #708",
    "photoUrl": "teacher.jpg",
    "experiences": [
        "國立中興大學副校長 (2021/2~2023/7)",
        "國家太空中心主任 (2018/2~2021/1)",
        "國立中興大學副校長 (2017~2018)",
        "科技部控制學門召集人 (2016~2018)",
        "國立中興大學中興講座教授 (2015~)",
        "國立中興大學副校長 (2012~2015)",
        "國立中興大學產學營運總中心主任 (2014~2015)",
        "國立中興大學校友中心主任 (2013~2015)",
        "國立中興大學講座教授 (2011~2015)",
        "國立中興大學特聘教授 (2007~2011)",
        "國立中興大學電機系主任 (2008~2010)",
        "國立中興大學研發處副研發長 (2006~2008)",
        "國立中興大學頂尖大學計畫執行秘書 (2005~2006)",
        "國立中興大學研發處學術發展組組長 (2004~2006)",
        "國立中興大學教授 (2003~2007)",
        "逢甲大學自控系副教授, 教授 (1995~2003)",
        "中科院助理研究員 (1991~1995)",
        "應機電子公司設計工程師 (1983~1985)",
        "林電機公司電子工程師 (1982~1983)"
    ],
    "honors": [
        "史丹福大學全球前2%頂尖科學家 (2021、2022)",
        "中華民國自動控制學會卓越服務貢獻獎 (2021)",
        "中興大學產學合作優良獎 (2010、2013、2017)",
        "中興大學特別貢獻獎 (2008)",
        "中興大學特別貢獻獎 (2006)",
        "國科會(科技部)傑出特約研究員獎",
        "國科會(科技部)傑出研究員獎 (2000、2002、2011)",
        "教育部師鐸獎表揚狀 (2015)",
        "教育部第五十八屆學術獎 (2014)"
    ],
    "services": [
        "Supervisor-Member of Board of Governors (BoGs): IEEE Taipei Section (2017~2018)",
        "Vice President, Chinese Automatic Control Society (2016~)",
        "Member of Board of Governors (BoGs): Chinese Automatic Control Society (2006~)",
        "Director-Member of Board of Governors (BoGs): IEEE Taipei Section (2015~2016)",
        "Chair: IEEE Control Systems Society, Taipei Chapter (2012~2015)",
        "Chair: IEEE Control Systems Society, Taipei Chapter (2009~2011)",
        "Vice Chair: IEEE Control Systems Society, Taipei Chapter (2003-2005)",
        "Technical Committee Member-International Association of Science and Technology for Development (IASTED) (2004~)",
        "Organizing Committee Member-IEEE Conference on Industrial Electronics and Applications (ICIEA) (2009, 2010, 2011, 2012)",
        "Fuzzy Systems Technical Committee Member: IEEE Computational Intelligence Society (CIS) (2013~).",
        "Program Committee Member: 2004 IEEE International Conference on Control Applications (Taipei)",
        "Best Paper Award Chair: 2005 International Conference on Automation Technology (Taichung)",
        "Best Paper Award Chair: 2007 CACS International Automatic Control Conference (Taiwan)",
        "Invited Session Speaker: 2010 IEEE International Conference on Control & Automation (ICCA’10) (Xiamen)",
        "General Chair: 2010 IEEE Conference on Industrial Electronics and Applications (ICIEA’10) (Taichung)",
        "International Advisory Committee Member: 2011 IEEE Conference on Industrial Electronics and Applications (ICIEA’11) (Beijing)",
        "Workshop Chair: 2011 Asian Control Conference (ASCC’11) (Kaohsiung)",
        "Program Committee Member: 2011 Asian Control Conference (ASCC’11) (Kaohsiung)",
        "Program Committee Member: 2011 IEEE International Symposium on Intelligent Control (ISIC’11) (Denver)",
        "Invited Speaker/Organizer: 2010 Workshop on Recent Advances in Control and Robotics, IEEE Control Systems Society, Taipei Chapter (Taichung)",
        "Invited Speaker: 2010 Workshop of Dynamics and Control for Biological Systems, Chinese Academy of Sciences (Shanghai)",
        "Invited Speaker: 2011 Symposium of Cutting-edge Engineering Education through Introducing Practice-Based Active Learning (Nagoya)",
        "Program Committee Member: The 30th Chinese Conference (CCC’11) (Yantai)",
        "Program Committee Member: The 31th Chinese Conference (CCC’12) (Hefei)",
        "General Chair: 2011 Symposium for Control Program of NSC/SIRCon2011 (Taichung)",
        "Program Co-Chair: 2012 National Symposium on System Science and Engineering (NSSSE’12) (Keelung)",
        "Technical Program Committee Member: IEEE TENCON 2012",
        "Workshop Speaker: IEEE Multi-Conference on Systems and Control (IEEE MSC 2012) (Duvornick)",
        "Program Co-Chair: 2013 National Symposium on System Science and Engineering (NSSSE’13) (Taipei)",
        "Program Committee Member: The 2nd International Conference on Robot Intelligence Technology and Applications 2013 (RiTA2013) (Denver)",
        "Fuzzy Systems Technical Committee Member: 2013 IEEE Computational Intelligence Society (CIS).",
        "Fuzzy Systems Technical Committee Member: 2014 IEEE Computational Intelligence Society (CIS).",
        "Invited Speaker: 2013 Joint Workshop on Systems and Control (Nanzan University, Nagoya)",
        "Invited speaker. 2013 Wiley Author Workshop, Dec. 12, 2013 (Taichung)",
        "Program Committee Member: 2014 IEEE International Conference on Fuzzy Systems (Beijing)",
        "General Chair: 2014 IEEE Conference on Control & Automation Industrial Electronics and Applications (ICCA’14) (Taichung)",
        "Research Project Evaluation Committee Member. Latvian Science Council, Lativia (2012~).",
        "Steering Committee Member-International Research-Intensive Center of Excellence (I-RICE), MOST, TAIWAN (2013~2016)",
        "Program Committee Member-2014 International Conference on Computer and Communication Technology (ICCCT’14), (Paris, France)",
        "Organizer: 2014 Workshop on Advances in Nonlinear Dynamical Systems and Robotics, June 17, 2014, IEEE Control Systems Society, Taipei Chapter (Taichung).",
        "Guest Speaker: 2015 Symposium of “Towards a Smart Future-Infinite Evolution”, March 2, 2015 (Garden Hotel, Taipei)",
        "Organizing Committee Member, International Conference and Exhibition on Control System, November 03-05, 2015 (Beijing, China).",
        "Technical Program Committee Member, IEEE International Conference on Computing, Communication & Automation, May 15-16, 2015 (Greater Noida, India)",
        "Program Committee Member, International Conference on Computer and Computational Sciences (ICCCA-2015), 2015 (Uttar Pradesh, India)",
        "Program Committee Member - 2015 IEEE International Conference on Fuzzy Systems (FUZZ-IEEE 2015), 2015 (Istanbul, Turkey)",
        "Program Committee Member, International Conference on Computer and Computational Sciences (ICCCA-2016), 2016 (Uttar Pradesh, India)",
        "Distinguished Invited Lecturer-IEEE International Conference of Industrial Electronics and Applications (ICIEA 2016), 2016 (Heifei)",
        "Keynote Speaker-銀髮智慧生活與健康照護研討會, 2016 (Changhua)",
        "Best Paper Award Chair: 2016 CACS International Automatic Control Conference (Taiwan)",
        "Program Committee Member, International Conference on Computer and Computational Sciences (ICCCA-2017), 2017 (Uttar Pradesh)",
        "Keynote Speaker, National Symposium on System Science and Engineering, 2017 (Taipei)",
        "General Co-Chair, NSSSE 2017, 2017 (Taipei)",
        "Keynote Speaker-科技部大眾科學教育專題講座-分享大師視野, 2017 (國立自然科學博物館)",
        "Keynote Speaker, The 12th Intelligent Living Technology Conference, 2017 (Taichung)",
        "Technical Committee Member, IEEE Congress on Evolutionary Computation, 2018 (Brazil)",
        "General Chair, The 4th International Conference on GPS Radio Occultation, 2018 (Taipei)",
        "General Chair, Astronautical Exploration Technology Workshop, 2018 (Hsinchu)",
        "Keynote Speaker, 2018 Up3 to Space International Symposium, 2018 (Tainan)",
        "Keynote Speaker, 科技部2018秋季「展望」系列演講, 2018 (Taipei)",
        "Invited Speaker, 中華民國航空測量及遙感探測學會會員大會, 2018 (Taipei)",
        "Invited Speaker, Taipei Conference of International Air and Space Law, 2019 (Taipei)",
        "Keynote Speaker, The 10th Asian-Pacific Conference on Aerospace Technology and Science &The 4th Asian Joint Symposium on Aerospace Engineering, 2019 (Hsinchu)",
        "Technical Committee Member, International Conference on Advances in Artificial Intelligence (ICAAI), 2019 (Istanbul, Turkey)",
        "General Chair, International Conference on Astronautics and Space Exploration (iCASE), 2019 (Hsinchu)",
        "Invited Speaker, PeruSAT-1: Lecciones Aprendidas-2019, Nov. 26, 2019 (Lima, Peru)",
        "Invited Speaker, Space Agency of Paraguay, Nov. 2019 (Asuncion, Paraguay)",
        "Advisory Committee Member, IEEE International Conference of Industrial Electronics and Applications (ICIEA), 2020 (Kristiansand, Norway)",
        "Honorary Chair of Program Committee, The 2020 International Automatic Control Conference, 2020 (Hsinchu)",
        "General Chair, The 5th International Conference on GPS Radio Occultation, 2020 (Hsinchu)",
        "Invited Speaker, 積彭講座, 核能研究所, Dec. 7, 2020 (Taoyuan)",
        "Keynote Speaker, iCASE2020暨2020航太學會學術研討會, Nov. 14, 2020 (Hsinchu)",
        "Invited Speaker, The 4th Paraguayan Space Conference, Paraguay Space Agency, Nov. 10, 2020 (Paraguay)",
        "Invited Speaker, Programa Internacional de Webinars sobre TECHNOLOGIA ESPACIAL, Nov. 2, 2020 (Peru)",
        "Keynote Speaker-第18屆週日閱讀科學, Sep. 20, 2020 (國立科學工藝博物館)",
        "Invited Speaker, 中央研究院物理研究所通俗演講, Nov. 10, 2020. (Nangang)",
        "Keynote Speaker, 衛星科學工作坊, Nov. 20, 2020. (Chungli)",
        "Invited Speaker, 台灣太空黑客松專題演講, Mar. 2021. (國立自然科學博物館)"
    ],
    "publications": [
        "C. L. Lin, Z. T. Sun and Y. Y. Chen , “Air-mattress system for ballistocardiogram-based heart rate and breathing rate estimation,” Heliyon, vol. 1, no. 9, 12 2022. (SCI)",
        "Y. Zhang, W. Chen, C. L. Lin, Z. Pei, J. Chen and D. Wang , “Synchronous analyses between electroencephalogram and surface electromyogram based on motor imagery and motor execution,” Review of Scientific Instruments, 11 2022. (SCI)",
        "J. J. Kao, C. L. Lin and J. Yang , “Adaptive wireless power transfer system with relay transmission and communication,” IEEE Transactions on Power Electronics, 10 2022. (SCI)",
        "D. Y. Huang, C. L. Lin and Y. Y. Chen , “Securable networked scheme with face authentication,” IET Biometrics, 09 2022. (SCI)",
        "C. M. Chang, C. L. Lin, B. Huang and Y. Zhang , “Image based control of smart workout systems,” Biomedical Signal Processing and Control, 08 2022. (SCI)",
        "C. Y. Chen, C. L. Lin and Y. Y. Chen , “Realization of ideal architecture of IoTs,” ARRAY, 07 2022. (SCI)",
        "C. L. Lin, J. C. Li, C. L. Chiu, Y. W. Andy Wu and Y. W. Jan , “Gyro-stellar inertial attitude estimation for satellite with high motion rate,” The Aeronautical Journal, 04 2022. (SCI)",
        "B. Huang, W. Chen, C. L. Lin, C. F. Juang and J. Wang , “MLP-BP: A novel framework for cuffless blood pressure measurement,” Biomedical Signal Processing and Control, 03 2022. (SCI)",
        "B. Huang, W. Chen, C. L. Lin, C. F. Juang, Y. Xing, Y. Wang and J. Wang , “A neonatal dataset and benchmark for non-contact neonatal heart rate monitoring based on spatio-temporal neural networks,” Engineering Applications of Artificial Intelligence, 11 2021. (SCI)",
        "Y. Zhang, W. Chen, C. L. Lin, Z. Pei, J. Chen and Z. Chen , “Boosting-LDA algorithm with multi-domain feature fusion for motor imagery EEG decoding,” Biomedical Signal Processing and Control, 09 2021. (SCI)",
        "Y. C. Lin, C. L. Lin, S. T. Huang and C. H. Kuo , “Implementation of an autonomous overtaking system based on time to lane crossing estimation and model predictive control,” Electronics, 09 2021. (SCI)",
        "B. Huang, C. L. Lin, W. Chen, C. F. Juang and X. Wu , “A novel one-stage framework for visual pulse rate estimation using deep neural networks,” Biomedical Signal Processing and Control, 08 2021. (SCI)",
        "J. J. Kao, C. L. Lin, Y. C. Liu, C. C. Huang and H. S. Jian , “Adaptive bidirectionally inductive power and data transmission system,” IEEE Transactions on Power Electronics, 07 2021. (SCI)",
        "Z. A. Shen, J. Cheng, C. T. Tang, C. L. Lin and C. F. Juang , “Estimation of machine cutting tool wear,” Journal of the Chinese Institute of Engineers, 05 2021. (SCI)",
        "C. H. Tu, Y. C. Chang, C. L. Lin and V. T. Liu , “Motor driving/braking control scheme with integration of multiple driving components,” Asian Journal of Control, 12 2020. (SCI)",
        "T. H. Chen, C. H. Tu, C. L. Lin and S. P. Hsu , “Advanced stabilizing control for electric scooters,” Asian Journal of Control, vol. 1, no. 32, pp. 20-31, 10 2020. (SCI)",
        "T. H. Chen, C. H. Tu, C. L. Lin and S. P. Hsu , “Advanced tracking control for electric vehicles,” Asian Journal of Control, vol. 3, no. 23, 10 2020. (SCI)",
        "S. M. Liu, C. H. Tu, C. L. Lin and V. T. Liu , “Field-oriented driving/braking control for electric vehicles,” Electronics, vol. 9, no. 9, 09 2020. (SCI)",
        "T. Jennawasin, C. L. Lin and D. Banjerdpongchai , “Parameter-dependent linear matrix inequality approach to robust state estimation of noisy genetic networks,” Computers and Chemical Engineering, no. 136, 03 2020. (SCI)",
        "Changchen Zhao, Weihai Chen, Chun-Liang Lin and Xingming Wu, “Physiological Signal Preserving Video Compression for Remote Photoplethysmography,” IEEE SENSORS JOURNAL, vol. 12, no. 19, pp. 4537-4548, 12 2019. (SCI)"
    ]
};


export const DEFAULT_GALLERY_CONTENT = {
    items: Array.from({ length: 10 }, (_, index) => ({
        id: `gallery-${index + 1}`,
        src: `front_cover/lab-bg${index + 1}.jpg`,
        caption: `活動照片 ${index + 1}`
    }))
};
